import PocketBase from 'pocketbase';
import type { TypedPocketBase } from './pocketbase-types'; // Generated by pocketbase-typegen

// Usage:
// 1. Generate types: npx pocketbase-typegen --db ./pb_data/data.db --out src/lib/pocketbase-types.ts
// 2. Copy this file to src/lib/pocketbase.ts
// 3. Update the URL below or use env var

export const pb = new PocketBase(
	import.meta.env.VITE_PB_URL || 'http://127.0.0.1:8090'
) as TypedPocketBase;

// Global auth store syncing
pb.authStore.onChange(() => {
	// Optional: Sync with SvelteKit cookie or local store
	console.log('Auth state changed', pb.authStore.isValid);
});
